### PR TITLE
fix/update_protobuf_dependency_version

### PR DESCRIPTION
**Pull request by aarmoa**
- Updated `protobuf` dependency version to ">=5.26.1"

## Summary by CodeRabbit

- **Documentation**
  - Updated the project to version 1.5.2.
- **Chores**
  - Updated the `protobuf` dependency to ensure compatibility and security with version 5.26.1 or newer.

### CODE REVIEW

**Comment by MiccWan** [comment]
Will this patch version be released to PyPI? It would be great if we could avoid setting the dependency version manually.

**Comment by aarmoa** [comment]
> Will this patch version be released to PyPI? It would be great if we could avoid setting the dependency version manually.

It has already been merged in the `master` branch and also published in PyPi.
PR: https://github.com/InjectiveLabs/sdk-python/pull/324
Release: https://github.com/InjectiveLabs/sdk-python/releases/tag/v1.5.1

**Comment by MiccWan** [comment]
I am referring to version 1.5.2. Specifying the dependency version ensures that our CI the correct version. Otherwise, we would need to manually add the protobuf dependency to our requirements.txt.

**Comment by aarmoa** [comment]
I see, I get you now. I will publish a new version with the fix right away.

**Pull request merged**
